name: Deploy Flood Lens to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci || npm install

      - name: Build for GitHub Pages
        env:
          VITE_PUBLIC_BASE: /flood-lens-nasa/
          VITE_FORCE_MANUAL_MODE: "true"   # no backend on Pages
          VITE_API_BASE_URL: ""
        run: |
          npm run build
          # Sanity check: built HTML must NOT reference src/main.tsx
          test -f dist/index.html
          if grep -q "src/main.tsx" dist/index.html; then
            echo "Build failed: dist/index.html still references src/main.tsx"; exit 1
          fi
          # SPA essentials
          cp index.html dist/404.html || true
          touch dist/.nojekyll
          ls -lah dist | sed -n '1,80p'

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          force_orphan: true
