name: Refresh data every 3h & Deploy Pages

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  PYTHON_ENTRY: "python -m pipeline.run_city"
  OUTPUT_DIR: "public/data"
  CITIES: "alexandria cairo khartoum lagos tunis casablanca beirut nairobi mumbai dhaka jakarta manila bangkok karachi ho_chi_minh"
  ALWAYS_OVERWRITE: "1"

jobs:
  refresh-data:
    name: Build fresh city data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python deps (if any)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Ensure output dir exists
        run: mkdir -p "$OUTPUT_DIR"

      - name: Choose city list
        id: cities
        shell: bash
        run: |
          if [ -f cities.txt ]; then
            echo "list=$(tr '\n' ' ' < cities.txt)" >> $GITHUB_OUTPUT
          else
            echo "list=$CITIES" >> $GITHUB_OUTPUT
          fi

      - name: Run pipeline for each city (real data if available)
        shell: bash
        env:
          PYTHON_ENTRY: ${{ env.PYTHON_ENTRY }}
        run: |
          set -euo pipefail
          echo "Cities: ${{ steps.cities.outputs.list }}"
          for CITY in ${{ steps.cities.outputs.list }}; do
            echo "=== Running for $CITY ==="
            $PYTHON_ENTRY --city "$CITY" --days 3 --write || true
          done

      - name: Seed/overwrite model data so UI is always filled (safe mock)
        shell: bash
        env:
          OUTPUT_DIR: ${{ env.OUTPUT_DIR }}
          CITIES: ${{ steps.cities.outputs.list }}
          ALWAYS_OVERWRITE: ${{ env.ALWAYS_OVERWRITE }}
        run: |
          python scripts/seed_model_data.py

      - name: Commit refreshed + seeded data (rebase & retry on conflicts)
        shell: bash
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Stage changes (ok if nothing changed)
          git add "$OUTPUT_DIR" || true
          if git diff --cached --quiet; then
            echo "No data changes to commit."
          else
            git commit -m "chore(data): refresh/seed (overwrite) model data [skip ci]"
          fi

          # Determine current branch (handles Main/main naming)
          TARGET_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          echo "Target branch: $TARGET_BRANCH"

          # Always rebase onto remote tip, then push. Retry up to 3 times.
          git fetch origin "$TARGET_BRANCH"
          for attempt in 1 2 3; do
            echo "Push attempt $attempt"
            # Rebase local commits onto remote tip
            git pull --rebase origin "$TARGET_BRANCH" || true
            if git push origin "HEAD:$TARGET_BRANCH"; then
              echo "Push succeeded."
              break
            fi
            if [ "$attempt" -eq 3 ]; then
              echo "Push failed after 3 attempts."
              exit 1
            fi
            sleep 2
          done

  build:
    name: Build Vite site
    runs-on: ubuntu-latest
    needs: refresh-data
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
